# Generated by Django 3.0.8 on 2023-02-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20230226_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.QuestionTest'),
        ),
    ]
