# Generated by Django 3.0.8 on 2023-02-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_adminstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminStudent',
        ),
    ]
